project:
  type: website
  pre-render: ./pre-render.R

website:
  title: "aoc2025"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Daily Challenges"
        href: daily-challenges.qmd
      - text: "About"
        href: about.qmd

  page-footer:
    background: "#F8F8F8"  # Set a light gray background color
    center:
      - text: "aoc2025 for esimms999"
    right:
      - icon: github
        href: https://github.com/esimms999/aoc2025

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
