project:
  type: website
  output-dir: _site
  resources:
    - quarto/

website:
  title: "aoc2025"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Day"
        menu:
          - href: day01.qmd
            text: "Day 01"
          - href: day02.qmd
            text: "Day 02"
      - text: "About"
        href: about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
