project:
  type: website
  pre-render: ./pre-render.R

website:
  title: "aoc2025"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Day"
        menu:
          - href: day01.qmd
            text: "Day 01"
          - href: day02.qmd
            text: "Day 02"
          - href: day03.qmd
            text: "Day 03"
          - href: day04.qmd
            text: "Day 04"
          - href: day05.qmd
            text: "Day 05"
      - text: "About"
        href: about.qmd

  page-footer:
    background: "#F8F8F8"  # Set a light gray background color
    center:
      - text: "aoc2025 for esimms999"
    right:
      - icon: github
        href: https://github.com/esimms999/aoc2025

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
