project:
  type: website

website:
  title: "aoc2025"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: day.qmd
        text: Day
      - href: about.qmd
        text: About

   sidebar:
     - title: "Day"
       style: docked
       contents:
         - day01.qmd
         - day02.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



